define(["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    /**
     * Specifies the File Manager internal variables
     */
    /** @hidden */
    exports.isFile = 'isFile';
    /**
     * Specifies the File Manager internal events
     */
    /** @hidden */
    exports.modelChanged = 'model-changed';
    /** @hidden */
    exports.initialEnd = 'initial-end';
    /** @hidden */
    exports.finalizeEnd = 'finalize-end';
    /** @hidden */
    exports.createEnd = 'create-end';
    /** @hidden */
    exports.filterEnd = 'filter-end';
    /** @hidden */
    exports.beforeDelete = 'before-delete';
    /** @hidden */
    exports.pathDrag = 'path-drag';
    /** @hidden */
    exports.deleteInit = 'delete-init';
    /** @hidden */
    exports.deleteEnd = 'delete-end';
    /** @hidden */
    exports.refreshEnd = 'refresh-end';
    /** @hidden */
    exports.resizeEnd = 'resize-end';
    /** @hidden */
    exports.splitterResize = 'splitter-resize';
    /** @hidden */
    exports.pathChanged = 'path-changed';
    /** @hidden */
    exports.destroy = 'destroy';
    /** @hidden */
    exports.beforeRequest = 'before-request';
    /** @hidden */
    exports.upload = 'upload';
    /** @hidden */
    exports.skipUpload = 'skip-upload';
    /** @hidden */
    exports.afterRequest = 'after-request';
    /** @hidden */
    exports.download = 'download';
    /** @hidden */
    exports.layoutRefresh = 'layout-refresh';
    /** @hidden */
    exports.actionFailure = 'actionFailure';
    /** @hidden */
    exports.search = 'search';
    /** @hidden */
    exports.openInit = 'open-init';
    /** @hidden */
    exports.openEnd = 'open-end';
    /** @hidden */
    exports.selectionChanged = 'selection-changed';
    /** @hidden */
    exports.selectAllInit = 'select-all-init';
    /** @hidden */
    exports.clearAllInit = 'clear-all-init';
    /** @hidden */
    exports.clearPathInit = 'clear-path-init';
    /** @hidden */
    exports.layoutChange = 'layout-change';
    /** @hidden */
    exports.sortByChange = 'sort-by-change';
    /** @hidden */
    exports.nodeExpand = 'node-expand';
    /** @hidden */
    exports.detailsInit = 'details-init';
    /** @hidden */
    exports.menuItemData = 'menu-item-data';
    /** @hidden */
    exports.renameInit = 'rename-init';
    /** @hidden */
    exports.renameEndParent = 'rename-end-parent';
    /** @hidden */
    exports.renameEnd = 'rename-end';
    /** @hidden */
    exports.showPaste = 'show-paste';
    /** @hidden */
    exports.hidePaste = 'hide-paste';
    /** @hidden */
    exports.selectedData = 'selected-data';
    /** @hidden */
    exports.cutCopyInit = 'cut-copy-init';
    /** @hidden */
    exports.pasteInit = 'paste-init';
    /** @hidden */
    exports.pasteEnd = 'paste-end';
    /** @hidden */
    exports.cutEnd = 'cut-end';
    /** @hidden */
    exports.hideLayout = 'hide-layout';
    /** @hidden */
    exports.updateTreeSelection = 'update-tree-selection';
    /** @hidden */
    exports.treeSelect = 'select-node';
    /** @hidden */
    exports.sortColumn = 'sort-column';
    /** @hidden */
    exports.pathColumn = 'path-column';
    /** @hidden */
    exports.searchTextChange = 'search-change';
    /** @hidden */
    exports.beforeDownload = 'before-download';
    /** @hidden */
    exports.downloadInit = 'download-init';
    /** @hidden */
    exports.dropInit = 'drop-init';
    /** @hidden */
    exports.dragEnd = 'drag-end';
    /** @hidden */
    exports.dropPath = 'drop-path';
    /** @hidden */
    exports.dragHelper = 'drag-helper';
    /** @hidden */
    exports.dragging = 'dragging';
    /** @hidden */
    exports.updateSelectionData = 'update-selection-data';
    /** @hidden */
    exports.methodCall = 'method-call';
    /** @hidden */
    exports.permissionRead = 'read';
    /** @hidden */
    exports.permissionEdit = 'write';
    /** @hidden */
    exports.permissionEditContents = 'writeContents';
    /** @hidden */
    exports.permissionCopy = 'copy';
    /** @hidden */
    exports.permissionUpload = 'upload';
    /** @hidden */
    exports.permissionDownload = 'download';
});
